### ISSUE TITLE
AddorRep

### ISSUE THREAD

**Issue by senioi** [Birnsen/KVLite#1]
Add or replace:  INSERT OR REPLACE
What is the fastest way to calculate the record COUNT?

**Comment by Birnsen** [comment]
That is a issue I not have thought to much about for now. We can probably add some method which counts all DBs in parallel in the "back-end".

I am a little bit short on time at the moment. In the meantime you can use the Get() method and count it via LINQ. Like so:

```
var kvl = KVLite.CreateInMemory();
var count = await kvl.Get().CountAsync();
```
